server:
  port: 5000

spring:
  application:
    name: user-service

  jpa:
    properties:
      hibernate:
        default_schema: users

  config:
    import: optional:configserver:http://localhost:8888